language: python
os:
- linux
python:
- '3.6'
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y ppa:openjdk-r/ppa
- sudo apt-get -qq update
- sudo apt-get install -y openjdk-8-jdk
- sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
- export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
- sudo apt-get install -y gcc-4.9 g++-4.9
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave
  /usr/bin/g++ g++ /usr/bin/g++-4.9
- sudo apt-get install -y libgomp1
install:
- pip install .
- pip install tensorflow==1.14 keras xgboost matplotlib ipython
script: python setup.py nosetests
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: iVB34uR2CL/Hn+lXEcipt4sGK5a8hZEfW8o0DeEZHh6NPO+ykkOjUfavlGBGFj2YBHXHobeNDgNF63+g37oxaIz8UOvp6MZtcuxzNUBuYvzkOSkOevQFttLJCQuVoa1dgfOur0zi2Q0U0xJzqNPoUEeL3x15yM+WXrB0+blYaBKt9y2VqMztlJExMGzZS6N4cccm8YdGSkt6dKovVvzR6ShTT/dIVmeuaVzVkJ6NLS7aw8i71I7zxxF7+K86tlWm8+L/LteyJyLhENVO614el6RxYFoKrLwYthIqnLMwxpZktVejymkW1BhaZvjIUwq7nqGGm9CklZpbDWNs2VP+UUmC1ziYuA/D/zPQy8GI712aZguTlF0gJa1diqLkzDwNIBcPV2xYlbipbkAExzgZnm7yKs9x3wRKDw2GJsYHeE1NvNJR8SN7MeUbICmekHHzQ6yr9B0ZfjHNjLmBKaFavwB8jEHj0u/2PBmtgLL8j2kL8hXoI/jPnihbUQ4nog/WkGQCCOh940zhq5AtZrwxxDmwl2zSwAJiICri6ah10c+1As1kncps4ip23d7WbxcFfYpRb+kn8NS9X9NX1D6c1cFggt96zPVkQ3BAW4vHaXCKxqKw8fZ0cDYK3A6IKdzSauLiTv8bVl7wI/1yATBkjsIjT00p5zg8jvl8jK+BQ8o=
  on:
    tags: true
  distributions: "sdist" # bdist_wheel breaks because pipy rejects linux wheels
  skip_cleanup: true
  skip_existing: true