language: python
os:
  - linux
python:
  - '3.6'
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install -y gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo apt-get install -y libgomp1
install:
  - pip install .
  - pip install tensorflow keras xgboost
script: python setup.py nosetests
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
# deploy:
#   provider: pypi
#   user: "shap_poster"
#   password:
#     secure: $Some_Variable
#     tags: true
#   distributions: "sdist bdist_wheel"
