[package]
name = "shap-cext-gpu"
version = "0.1.0"
edition = "2021"

[lib]
name = "_cext"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
numpy = "0.23"
ndarray = "0.16"
